<?php
/**
 * @copyright Copyright (c) 2013 2amigOS! Consulting Group LLC
 * @link http://2amigos.us
 * @license http://www.opensource.org/licenses/bsd-license.php New BSD License
 */
namespace cabbage\kindeditor;

use yii\web\AssetBundle;
use Yii;

class MultiImageAsset extends AssetBundle
{
    public $depends = [
        "cabbage\\kindeditor\\KindEditorAsset",
    ];
    public function init()
    {
        $this->sourcePath = __DIR__ . "/bower_components";

        $this->js = [
          'multi-images/js/insertImage.js'
        ];
        $this->css = [
            'multi-images/css/insertImage.css'
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}